apiVersion: v1
kind: Service
metadata:
  name: {{ include "authproxy.fullname" . }}
  labels:
    {{- include "authproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    component: {{ include "authproxy.fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
